INSERT INTO TRABALHO(ID,CARGO, FUNCAO, SALARIO) VALUES(1, 'Desenvolvedor', 'Desenvolvedor full stack', 7000);
INSERT INTO TRABALHO(ID,CARGO, FUNCAO, SALARIO) VALUES(2, 'Web Design', 'Web Design', 7000);

INSERT INTO PESSOA(ID, LOGIN, NOME, PASSWORD, TRABALHO_ID) VALUES(1,'wagnerpaulino','Wagner Paulino','123',1);
INSERT INTO PESSOA(ID, LOGIN, NOME, PASSWORD, TRABALHO_ID) VALUES(2,'jopaulino','Jo Paulino','123',1);
INSERT INTO PESSOA(ID, LOGIN, NOME, PASSWORD, TRABALHO_ID) VALUES(3,'tupaulino','Tu Paulino','123',1);
INSERT INTO PESSOA(ID, LOGIN, NOME, PASSWORD, TRABALHO_ID) VALUES(4,'larpaulino','la Paulino','123',2);
INSERT INTO PESSOA(ID, LOGIN, NOME, PASSWORD, TRABALHO_ID) VALUES(5,'paulpaulino','paul Paulino','123',2);

